### ISSUE TITLE
Gather Contributors List

### ISSUE THREAD

**Issue by StanleySweet** [0ADMods/kushites#10]
If one could gather the list of all contributors for the credits, that'd be great

**Comment by StanleySweet** [comment]
Artwork By: LordGood, wowgetoffyourcellphone, Stan, wackyserious, Lion.Kanzen, Sundiata, Alexandermb
History Research: Sundiata
Discussed With: mimo, Itms, niektb, WhiteTreePaladin, feneur, fabio, elexis, leper, Pureon, 
Templates Tweaks : elexis, Stan, Hannibal_Barca, mimo, Sundiata
Tested By: FeldFeld, (-_-), Grugnas, mapkoc, Dizaka, Cesar, Liberty, Sundiata
Reviewed by Stan

**Comment by Sundiata1** [comment]
Textures:
Kush shield texture sources

https://upload.wikimedia.org/wikipedia/commons/a/ad/Génisses_red_holstein_02.jpg
https://commons.wikimedia.org/w/index.php?title=Special:Search&limit=500&offset=0&profile=default&search=cow&searchToken=4dvrojliffadf3mi49s941t98#/media/File:Ku_med_horn.JPG
http://www.publicdomainpictures.net/view-image.php?image=120245&picture=lui-2
http://www.publicdomainpictures.net/view-image.php?image=241174&picture=young-cow-in-the-meadow
http://www.publicdomainpictures.net/view-image.php?image=131202&picture=oxen
http://www.publicdomainpictures.net/view-image.php?image=49951&picture=cows-03
https://commons.wikimedia.org/wiki/File:Leopard_fur-skin_1.JPG
http://www.publicdomainpictures.net/view-image.php?image=86914&picture=mad-cow
https://commons.wikimedia.org/wiki/File:Rhino_animal_grazing.jpg
https://upload.wikimedia.org/wikipedia/commons/a/ad/Génisses_red_holstein_02.jpg
http://www.publicdomainpictures.net/view-image.php?image=39132&picture=giraffe
http://www.publicdomainpictures.net/view-image.php?image=231351&picture=giraffe-skin
