### ISSUE TITLE
Kushite cotton or linen corselet

### ISSUE THREAD

**Issue by Sundiata1** [0ADMods/kushites#3]
One of the attires worn by Kushites is a type of linen or cotton corselet, widely used in the New Kingdom as a basic melee body armour (layered linen or cotton wrapped around the torso) and inherited by Kushites. This body "armour" should be used for 2nd tier citizen soldiers (swordsman, pikeman, Nubian cav):

Kushite examples of the corselet: 
![kush kushite corselet](https://user-images.githubusercontent.com/25348740/35157333-f4ae85da-fd33-11e7-9c6c-131de381c094.jpg)

Application of the corselet:
![kush corselet 2](https://user-images.githubusercontent.com/25348740/35157348-003bf14e-fd34-11e7-8651-7ccbb89e6a96.jpg)

**Comment by StanleySweet** [comment]
Fixed by wackyserious -> 6b3e8a80966d8b720265519bf588772e1e32baf6
