### ISSUE TITLE
Kushite Bronze Scale Armour Corselet

### ISSUE THREAD

**Issue by Sundiata1** [0ADMods/kushites#4]
The Kushite bronze scale armour corselet is richly illustrated in reliefs and would have been worn by the upper tiers of the Kushite army. The same design as the linen or cotton corselet, with the addition of a layer of bronze scales around the torso. Basically the armour for champion units (Napatan and Apedemak templeguards, Meroitic royal archers and Meroitic royal cavalry (lancers).

Kushite bronze scale armour corselets:
![kush bronze scale armour corselet](https://user-images.githubusercontent.com/25348740/35160123-8b027340-fd3c-11e7-98ac-62b13696f104.jpg)

Application of scale armour corselet:
![kush scale armour corselet 2](https://user-images.githubusercontent.com/25348740/35160146-9fb2d974-fd3c-11e7-8b81-c9c641cd34b5.jpg)

**Comment by StanleySweet** [comment]
Fixed by wackyserious -> 6b3e8a80966d8b720265519bf588772e1e32baf6
