### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by Jeeppler** [0ADMods/kushites#70]
Please add a license to this project. The licensing part is important otherwise you have to ask every single contributor for permission to use their work.

I assume you want to pick GPL-v2 for the source code, as other mods do it. However, I am not sure if the artwork (images) and sound can be under GPL-v2 as well. Otherwise, you might want to use a Creative Commons for art (images) and sound.

**Comment by StanleySweet** [comment]
Artwork is under CC-BY-SA 3.0 I don't know if you are aware, but they were committed in the main game, so this repository is only there for bugtracking because I find it easier than the forums :)

**Comment by Jeeppler** [comment]
@StanleySweet I am not sure if I understood your answer. Will the Kushites be in the main game or is this repository really a mod (external)? If it is a mod for 0 A.D. then it is important to provide a License for all the source code, even if the artwork is already in the main game and it should be mentioned under which license they are published. I mean other mods in the 0ADMods organization have a proper license, for example [Terra Magna](https://github.com/0ADMods/terra_magna/blob/master/License.txt).

**Comment by StanleySweet** [comment]
They literally are in the main game right now. I committed them myself :)

**Comment by Jeeppler** [comment]
@StanleySweet So, this repository is just a mirror?

**Comment by StanleySweet** [comment]
More like a personal bug tracler
